apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-init
data:
  init.sh: |
    #!/bin/bash
    set -e

    export PGUSER=${POSTGRES_USER}
    export PGPASSWORD=${POSTGRES_PASSWORD}

    echo "Waiting for PostgreSQL to be ready..."
    for i in {1..10}; do
      if pg_isready -U "$POSTGRES_USER" > /dev/null 2>&1; then
        echo "PostgreSQL is ready!"
        break
      else
        echo "Waiting for PostgreSQL..."
        sleep 3
      fi
    done

    echo "Checking if database 'users' exists..."
    if ! psql -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = 'users'" | grep -q 1; then
      echo "Database 'users' not found. Creating it..."
      psql -U "$POSTGRES_USER" -c "CREATE DATABASE users"
    else
      echo "Database 'users' already exists."
    fi

    echo "Running initialization script for 'users' database..."
    if [ -f /docker-entrypoint-initdb.d/users.sql ]; then
      psql -U "$POSTGRES_USER" -d users -f /docker-entrypoint-initdb.d/users.sql
    else
      echo "Initialization script not found at /docker-entrypoint-initdb.d/users.sql"
      exit 1
    fi
