apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-init
data:
  init.sh: |
    #!/bin/bash
    set -e

    echo "Waiting for PostgreSQL to be ready..."
    for i in {1..10}; do
      if psql -U "$PGUSER" -d "$POSTGRES_DB" -c '\q' 2>/dev/null; then
        echo "PostgreSQL is ready!"
        break
      else
        echo "Waiting for PostgreSQL..."
        sleep 3
      fi
    done

    echo "Checking if database 'users' exists..."
    psql -U "$PGUSER" -tc "SELECT 1 FROM pg_database WHERE datname = 'users'" | grep -q 1 || \
      (echo "Database 'users' not found. Creating it..."; psql -U "$PGUSER" -c "CREATE DATABASE users")

    echo "Running initialization script for 'users' database..."
    if [ -f /docker-entrypoint-initdb.d/users.sql ]; then
      psql -U "$PGUSER" -d users -f /docker-entrypoint-initdb.d/users.sql
    else
      echo "Initialization script not found at /docker-entrypoint-initdb.d/users.sql"
      exit 1
    fi
