apiVersion: v1
kind: Secret
metadata:
  name: cadvisor-scrape-config
  namespace: monitoring
type: Opaque
stringData:
  scrape-config.yaml: |
    - job_name: 'cadvisor'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: cadvisor
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: "8080"
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
