{
 "title": "Application Metrics",
 "tags": [
  "application",
  "metrics",
  "dashboard",
  "services",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "💚[K8s Services Health] - All Service Status",
   "type": "row",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authentication Service Status",
     "type": "stat",
     "gridPos": { "x": 0, "y": 0, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='authentication-service'}) OR on() vector(0)",
       "legendFormat": "Authentication Service Status"
      }
     ]
    },
    {
     "title": "Broker Service Status",
     "type": "stat",
     "gridPos": { "x": 4, "y": 0, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='broker-service'}) OR on() vector(0)",
       "legendFormat": "Broker Service Status"
      }
     ]
    },
    {
     "title": "Front-end Service Status",
     "type": "stat",
     "gridPos": { "x": 8, "y": 0, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='front-end'}) OR on() vector(0)",
       "legendFormat": "Front-end Service Status"
      }
     ]
    },
    {
     "title": "Listener Service Status",
     "type": "stat",
     "gridPos": { "x": 12, "y": 0, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='listener-service'}) OR on() vector(0)",
       "legendFormat": "Listener Service Status"
      }
     ]
    },
    {
     "title": "Logger Service Status",
     "type": "stat",
     "gridPos": { "x": 16, "y": 0, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='logger-service'}) OR on() vector(0)",
       "legendFormat": "Logger Service Status"
      }
     ]
    },
    {
     "title": "Mailer Service Status",
     "type": "stat",
     "gridPos": { "x": 20, "y": 0, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='mailer-service'}) OR on() vector(0)",
       "legendFormat": "Mailer Service Status"
      }
     ]
    },
    {
     "title": "Database Status (MongoDB)",
     "type": "stat",
     "gridPos": { "x": 0, "y": 6, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='mongo'}) OR on() vector(0)",
       "legendFormat": "Database Status (MongoDB)"
      }
     ]
    },
    {
     "title": "Database Status (PostgreSQL)",
     "type": "stat",
     "gridPos": { "x": 4, "y": 6, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='postgres'}) OR on() vector(0)",
       "legendFormat": "Database Status (PostgreSQL)"
      }
     ]
    },
    {
     "title": "Message Broker Status (RabbitMQ)",
     "type": "stat",
     "gridPos": { "x": 8, "y": 6, "w": 4, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='rabbitmq'}) OR on() vector(0)",
       "legendFormat": "Message Broker Status (RabbitMQ)"
      }
     ]
    }
   ]
  },
  {
   "title": "[K8s Workloads] - Authentication Service",
   "type": "row",
   "gridPos": { "x": 0, "y": 1, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum by(method, endpoint) (rate(auth_service_request_count[1m]))",
       "legendFormat": "{{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(auth_service_request_latency_seconds_bucket[1m])) by (le, method, endpoint))",
       "legendFormat": "p95 {{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "Error Count",
     "type": "graph",
     "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum by(method, endpoint) (rate(auth_service_error_count[1m]))",
       "legendFormat": "{{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "stat",
     "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{container=\"authentication-service\"}[1m])",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "Active Users (Successful Authentications)",
     "type": "graph",
     "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
     "yaxes": [
      { "format": "short", "label": "Active Users" }
     ],
     "targets": [
      {
       "expr": "increase(auth_service_request_count{method='POST'}[1m])",
       "legendFormat": "Successful Authentications"
      }
     ]
    },
    {
     "title": "Database Connection Status (PostgreSQL)",
     "type": "stat",
     "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='postgres'}) OR on() vector(0)",
       "legendFormat": "Postgres Connection Status"
      }
     ]
    },
    {
     "title": "Database Connection Status (MongoDB)",
     "type": "stat",
     "gridPos": { "x": 12, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='mongo'}) OR on() vector(0)",
       "legendFormat": "MongoDB Connection Status"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"authentication-service\"}[1m])",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "x": 0, "y": 24, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{container=\"authentication-service\"}) / 1024 / 1024",
       "legendFormat": "Memory Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "[K8s Workloads] - Broker Service",
   "type": "row",
   "gridPos": { "x": 0, "y": 2, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests Processed",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(broker_requests_total[1m]))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(broker_request_latency_seconds_bucket[1m])) by (le))",
       "legendFormat": "p95 Latency"
      }
     ]
    },
    {
     "title": "Error Count",
     "type": "graph",
     "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(broker_request_errors_total[1m]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "RabbitMQ Failures",
     "type": "graph",
     "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(broker_rabbitmq_failures_total[1m]))",
       "legendFormat": "RabbitMQ Failures"
      }
     ]
    },
    {
     "title": "gRPC & RPC Failures",
     "type": "graph",
     "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(broker_grpc_failures_total[1m]) + rate(broker_rpc_failures_total[1m]))",
       "legendFormat": "gRPC & RPC Failures"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "stat",
     "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{container=\"broker-service\"}[1m])",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"broker-service\"}[1m])",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "x": 12, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{container=\"broker-service\"}) / 1024 / 1024",
       "legendFormat": "Memory Usage MB"
      }
     ]
    }
   ]
  },
  {
   "title": "[K8s Workloads] - Front-end Service",
   "type": "row",
   "gridPos": { "x": 0, "y": 3, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum by(method, path) (rate(http_requests_total[1m]))",
       "legendFormat": "{{method}} | {{path}}"
      }
     ]
    },
    {
     "title": "Request Latency (95th percentile)",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, method, path))",
       "legendFormat": "p95 | {{method}} | {{path}}"
      }
     ]
    },
    {
     "title": "Request Status Code Distribution",
     "type": "graph",
     "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum by(status) (rate(http_requests_total[1m]))",
       "legendFormat": "Status Code {{status}}"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "stat",
     "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{container=\"front-end\"}[1m])",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "Request Size Distribution",
     "type": "graph",
     "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_size_bytes_bucket[1m])) by (le, method, path))",
       "legendFormat": "p90 | {{method}} | {{path}}"
      }
     ]
    },
    {
     "title": "Response Size Distribution",
     "type": "graph",
     "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_response_size_bytes_bucket[1m])) by (le, method, path))",
       "legendFormat": "p90 | {{method}} | {{path}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"front-end\"}[1m])",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "x": 12, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{container=\"front-end\"}) / 1024 / 1024",
       "legendFormat": "Memory Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "[K8s Workloads] - Listener Service",
   "type": "row",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RabbitMQ Connection Attempts",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rabbitmq_connection_attempts_total",
       "legendFormat": "Connection Attempts"
      }
     ]
    },
    {
     "title": "RabbitMQ Connection Errors",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rabbitmq_connection_errors_total",
       "legendFormat": "Connection Errors"
      }
     ]
    },
    {
     "title": "RabbitMQ Messages Processed",
     "type": "graph",
     "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rabbitmq_messages_processed_total",
       "legendFormat": "Messages Processed"
      }
     ]
    },
    {
     "title": "RabbitMQ Message Processing Duration (s)",
     "type": "graph",
     "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(rabbitmq_message_processing_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "p95 Message Duration"
      },
      {
       "expr": "sum(rate(rabbitmq_message_processing_duration_seconds_sum[1m])) / sum(rate(rabbitmq_message_processing_duration_seconds_count[1m]))",
       "legendFormat": "Average Message Duration"
      }
     ]
    },
    {
     "title": "RabbitMQ Message Processing Errors",
     "type": "graph",
     "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
     "targets": [
      { "expr": "rabbitmq_message_errors_total", "legendFormat": "Processing Errors" }
     ]
    },
    {
     "title": "RabbitMQ Connection Status",
     "type": "stat",
     "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='rabbitmq'}) OR on() vector(0)",
       "legendFormat": "RabbitMQ Connection Status"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"authentication-service\"}[1m])",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "x": 12, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{container=\"authentication-service\"}) / 1024 / 1024",
       "legendFormat": "Memory Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "[K8s Workloads] - Logger Service",
   "type": "row",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Insertions Total",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(logger_service_log_inserts_total[5m]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Log Insertion Errors",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(logger_service_log_insertion_errors_total[5m]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Log Insertion Duration (s)",
     "type": "graph",
     "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(logger_service_log_insertion_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p95 - {{status}}"
      }
     ]
    },
    {
     "title": "gRPC Request Duration (s)",
     "type": "graph",
     "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(logger_service_grpc_request_duration_seconds_bucket[5m])) by (le, method))",
       "legendFormat": "p95 - {{method}}"
      }
     ]
    },
    {
     "title": "Database Connection Status (MongoDB)",
     "type": "stat",
     "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "count(up{job='mongo'}) OR on() vector(0)",
       "legendFormat": "MongoDB Connection Status"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"logger-service\"}[1m]) * 100",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory Usage (MB)",
     "type": "stat",
     "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{container=\"logger-service\"}) / 1024 / 1024",
       "legendFormat": "Memory Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "[K8s Workloads] - Mailer Service",
   "type": "row",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mail Send Attempts",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(mailer_service_mail_send_attempts_total[5m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Mail Send Errors",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "sum(rate(mailer_service_mail_send_errors_total[5m]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Mail Send Duration (s)",
     "type": "graph",
     "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(mailer_service_mail_send_duration_seconds_bucket[5m])) by (le, status))",
       "legendFormat": "p95 - {{status}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"mailer-service\"}[1m]) * 100",
       "legendFormat": "CPU Usage"
      }
     ]
    },
    {
     "title": "Memory Usage (MB)",
     "type": "stat",
     "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{container=\"mailer-service\"}) / 1024 / 1024",
       "legendFormat": "Memory Usage"
      }
     ]
    }
   ]
  }
 ]
}