{
 "title": "Horizontal Pod Autoscaler (HPA)",
 "description": "Kubernetes (k8s) Horizontal Pod Autoscaler (HPA)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info, namespace)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{namespace=~\"$ns\"}, horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$hpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hpa" },
  {
   "title": "Target Metric ($hpa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "target ({{metric_name}}: {{metric_target_type}})"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}\n  and on(metric_name, metric_target_type)\n    kube_horizontalpodautoscaler_spec_target_metric{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current ({{metric_name}}: {{metric_target_type}})"
    }
   ]
  },
  {
   "title": "Replicas ($hpa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Status Condition",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_condition{namespace=~\"$ns\", horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{condition}}: {{status}}"
    }
   ]
  }
 ]
}