apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-monitoring-chart.fullname" . }}
  labels:
    {{- include "helm-monitoring-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm-monitoring-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-monitoring-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards/default
              readOnly: true
      volumes:
        - name: dashboards
          configMap:
            name: {{ include "helm-monitoring-chart.fullname" . }}-dashboards
